use_frameworks!

platform :ios, '8.0'

target 'MyLib_Example' do
  pod 'MyLib', :path => '../'

  target 'MyLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
